package io.tubeguardian.orchestrator.infrastructure.client.ingestion.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public record VideoResponseDto(
    VideoMetadataDto metadata, VideoTranscriptDto transcript, String status) {
  @JsonIgnoreProperties(ignoreUnknown = true)
  public record VideoMetadataDto(
      @JsonProperty("video_id") String videoId,
      String title,
      String channel,
      @JsonProperty("video_url") String videoUrl,
      @JsonProperty("thumbnail_url") String thumbnailUrl,
      @JsonProperty("duration_seconds") Integer durationSeconds,
      @JsonProperty("upload_date") String uploadDate) {}

  @JsonIgnoreProperties(ignoreUnknown = true)
  public record VideoTranscriptDto(
      String text,
      @JsonProperty("language_code") String languageCode,
      @JsonProperty("is_auto_generated") Boolean isAutoGenerated) {}
}
