spring:
  application:
    name: tg-policy-engine
  datasource:
    url: jdbc:postgresql://localhost:5432/${SPRING_DATASOURCE_DB}
    username: ${SPRING_DATASOURCE_USER}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

  ai:
    google:
      genai:
        api-key: ${GOOGLE_GENAI_API_KEY}
        model: gemini-embedding-001

    vectorstore:
      qdrant:
        host: ${SPRING_AI_VECTORSTORE_QDRANT_HOST:localhost}
        port: ${SPRING_AI_VECTORSTORE_QDRANT_PORT:6334}
        collection-name: garm_policies
        initialize-schema: true